#!/bin/bash
# quickly rebuild local cagee without running cmake config or tests
# jtourig / hahnlab 2023

set -euo pipefail

procs=$(( $(lscpu | grep '^CPU(s):' | awk '{print $2}') / 4 )) # get 1/4 of available CPUs (prob linux-only)

msg() { >&2 echo -e "  $@"; }
warn() { msg "WARNING: $1"; }
err() { msg "ERROR: $1"; msg "EXITING..."; exit 1; }
set_wd() { cd "${0%/*}" && msg "set current working dir to script dir:\n    ${PWD}/"; }

set_wd 				# go to CAGEE/utils/ dir
msg "Quick-building CAGEE from current local source..."

msg "removing existing install dir if present..."
{ [[ -d ../install/ ]] && rm -vr ../install/; } || msg '../install/ not found'

msg 'creating new build and install dirs...'
mkdir -vp ../install/
{ cd ../build/ && msg "moved to $PWD"; } || err "could not enter build dir"

msg "building CAGEE with $procs procs"
{ make -j "$procs" && make install; } || err "problem running make"
msg "CAGEE built and installed to CAGEE/install/bin/cagee"

msg "done quick-building local CAGEE !!"

exit
